import "./globals.css";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      // className={inter.className}
      >
        <header>
          <p>This is Header </p>
        </header>
        {children}
        <footer>
          <h2> This is Footer</h2>
        </footer>
      </body>
    </html>
  );
}
